[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#1a1a19"
secondaryBackgroundColor = "#232322"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
